CREATE DATABASE IF NOT EXISTS Whiteboard;
USE Whiteboard;

DROP TRIGGER IF EXISTS assignmentTrigger;

DROP PROCEDURE IF EXISTS getLogin;
DROP PROCEDURE IF EXISTS getCourses;
DROP PROCEDURE IF EXISTS courseInfo;
DROP PROCEDURE IF EXISTS materialInfo;
DROP PROCEDURE IF EXISTS announcementInfo;
DROP PROCEDURE IF EXISTS getAssignments;
DROP PROCEDURE IF EXISTS getSubmission;
DROP PROCEDURE IF EXISTS getAssGrade;
DROP PROCEDURE IF EXISTS getExGrade;
DROP PROCEDURE IF EXISTS getStudentInfo;

DROP PROCEDURE IF EXISTS addMaterial;
DROP PROCEDURE IF EXISTS addAnnouncement;
DROP PROCEDURE IF EXISTS addAnnouncement;
DROP PROCEDURE IF EXISTS addAssignment;
DROP PROCEDURE IF EXISTS addExam;
DROP PROCEDURE IF EXISTS addSubmission;
DROP PROCEDURE IF EXISTS gradeAssignment;
DROP PROCEDURE IF EXISTS gradeSubmission;
DROP PROCEDURE IF EXISTS gradeExam;

DROP PROCEDURE IF EXISTS delMaterial;
DROP PROCEDURE IF EXISTS delAnnouncement;
DROP PROCEDURE IF EXISTS delAssignment;
DROP PROCEDURE IF EXISTS delExam;

DROP FUNCTION IF EXISTS getFinalGrade;

DROP VIEW IF EXISTS compareAssignment;
DROP VIEW IF EXISTS compareExam;
DROP VIEW IF EXISTS assSubmit;

DROP TABLE IF EXISTS ClassAnnouncement,ClassMaterial,ExamGrade;
DROP TABLE IF EXISTS AssignmentSubmission,Exam;
DROP TABLE IF EXISTS AssignmentGrade;
DROP TABLE IF EXISTS Exam,Assignment;
DROP TABLE IF EXISTS TakenClasses;
DROP TABLE IF EXISTS Courses,Users;
